disabled_rules:
  - force_cast
  - force_try
  - identifier_name
  - vertical_parameter_alignment

included:
  - Katanga

excluded:
  - Katanga/Assets*
  - Katanga/*.lproj
  - Katanga/Resources
  - Katanga/Extensions/3rdparty

statement_position:
  statement_mode: uncuddled_else

large_tuple:
  warning: 4
  error: 5

