language: objective-c
os: osx
osx_image: xcode8

cache:
  - bundler
  - cocoapods

before_install:
   - bundle install
   - bundle exec pod repo update --silent

script:
   - bundle exec pod install
   - set -o pipefail
   - xcodebuild -workspace Katanga.xcworkspace -scheme Katanga -destination "platform=iOS Simulator,name=iPhone 6 Plus" | xcpretty
